### ISSUE TITLE
Spruce Cogwheel Recipe Missing [1.19.2]

### ISSUE THREAD

**Issue by mobiusdt** [Rabbitminers/Extended-Cogs#13]
The spruce cogwheel recipes (small and large) do not show up in JEI (only the conversions show up), and do not work in the crafting bench.

**Comment by Water-Cat1** [comment]
Deployer crafts are still there, but otherwise spruce cannot be used to make cogs in the crafting bench
![image](https://user-images.githubusercontent.com/10862949/210720508-d6160cda-c8b8-4f30-a177-28f36bb2d550.png)

**Comment by Rabbitminers** [comment]
I've added a backup recipe that will take the place of the crafting recipe if it doesnt load, everything should work in the next patch (1.1.2)
