### ISSUE TITLE
[1.19.2] Copper and iron large cogwheels cant be crafted from small cogwheels of the same type.

### ISSUE THREAD

**Issue by Water-Cat1** [Rabbitminers/Extended-Cogs#14]
Large copper and iron cogwheels are missing the craft upgrade from their smaller version:
![image](https://user-images.githubusercontent.com/10862949/210720959-708af723-c2d1-4910-b47b-5ea4d87bf451.png)

Possibly related the oak large cogwheel have crafts involving iron and copper ingots
![image](https://user-images.githubusercontent.com/10862949/210721141-0b07c3ee-1f68-4952-8f74-2c5d9efe1d5f.png)
![image](https://user-images.githubusercontent.com/10862949/210721170-e92cd22e-e17c-4310-a5c1-4a758981a265.png)

**Comment by Rabbitminers** [comment]
Thanks for notifying me I wasnt aware of the incorrect tags for iron and copper, those have also been patched, in the latest patch (1.1.2) which should be on curseforge in a few hours once it's approved
