### ISSUE TITLE
[1.19.2] Brass and andesite casing cannot be used on extended-cogs

### ISSUE THREAD

**Issue by Water-Cat1** [Rabbitminers/Extended-Cogs#15]
Brass and andesite casing, that can be used on normal Create cogs, cannot be used the same on cogs added by this mod.
![image](https://user-images.githubusercontent.com/10862949/210721975-50e1c9ee-d0c1-4991-a4dd-387e4cf08877.png)

**Comment by Rabbitminers** [comment]
This, isnt a bug. Currently its intentionally disabled to prevent them from being transformed back to spruce cogwheels when encased. This will be implemented in the future
