### ISSUE TITLE
[Bug] Brass cogwheel not register

### ISSUE THREAD

**Issue by EvanHsieh0415** [Rabbitminers/Extended-Cogs#23]
## Information
Mod Loader: `Quilt 1.19.2`
Mod Version: `1.19.2-0.5.0g-1.1.2`

## Logs
```
[Server thread/ERROR]: Couldn't parse loot table extendedcogs:blocks/brass_cogwheel
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'extendedcogs:brass_cogwheel'

...

[Server thread/ERROR]: Couldn't parse loot table extendedcogs:blocks/brass_cogwheel
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string ...
```

## Gallery
![Image](https://user-images.githubusercontent.com/74277414/224476539-ac6c0176-017a-4029-815b-9db622fc2001.png)

**Comment by Rabbitminers** [comment]
These where left over from where brass cogwheels where planned for initial release but got pushed back, these messages are fixed in the new beta releases and hopefully we'll come full circle with actual brass cogwheels in the next patch
