### ISSUE TITLE
[Bug] Recipe using the wrong tag

### ISSUE THREAD

**Issue by EvanHsieh0415** [Rabbitminers/Extended-Cogs#24]
## Information
Mod Loader: `Quilt 1.19.2`
Mod Version: `1.19.2-0.5.0g-1.1.2`

## How to fix:
- delete `#forge:ingots/steel` from recipes
- add `#c:steel_ingots` into recipes

## Logs
```
[Server thread/ERROR]: Parsing error loading recipe extendedcogs:crafting/large_steel_cogwheel_from_small
com.google.gson.JsonSyntaxException: Unknown item 'forge:ingots/steel'
```

## Gallery
![extendedcogs_crafting_large_steel_cogwheel](https://user-images.githubusercontent.com/74277414/224477682-8641fd34-0581-40ca-b69e-a318d99e7642.png)
![extendedcogs_crafting_steel_cogwheel](https://user-images.githubusercontent.com/74277414/224477684-2f39e0fa-1029-435b-98ac-3d049b02d54e.png)
![extendedflywheels_steel_flywheel](https://user-images.githubusercontent.com/74277414/224477687-cc1e32cb-b68a-47f5-a53b-b13e3ec2ae9d.png)

**Comment by Rabbitminers** [comment]
Patched for multi-loader release :)
