### ISSUE TITLE
Implementing new cogwheel materials through datapacks

### ISSUE THREAD

**Issue by Octelly** [Rabbitminers/Extended-Cogs#25]
I'm not that familiar with Java, but from what I can see, the cogwheel materials are currently hardcoded:
https://github.com/Rabbitminers/Extended-Cogwheels/blob/df0728a7a8e3e0df79bbe80bea0299a537b335d0/common/src/main/java/com/rabbitminers/extendedgears/base/data/WoodenCogwheel.java#L14-L22

I think it would be really cool, if the mod automatically generated the cogwheel items based on datapack information, the same you do recipes. ( https://github.com/Rabbitminers/Extended-Cogwheels/tree/df0728a7a8e3e0df79bbe80bea0299a537b335d0/common/src/main/resources )

**Comment by Rabbitminers** [comment]
Datapacks cannot load assets, perhaps kubejs or craft tweaker integration could be explored
