### ISSUE TITLE
Mod requires Flywheel on Server-side

### ISSUE THREAD

**Issue by SrRapero720** [Rabbitminers/Extended-Cogs#26]
Has far i know, create no needs Flywheel on Serverside
[crash-2023-03-21_01.43.40-fml.txt](https://github.com/Rabbitminers/Extended-Cogwheels/files/11024345/crash-2023-03-21_01.43.40-fml.txt)

**Comment by Rabbitminers** [comment]
This has been patched in the latest beta release

**Comment by SrRapero720** [comment]
i can't found the release on CF
is for 1.18.2??

**Comment by Rabbitminers** [comment]
Pre compiled beta releases are available on discord or you can wait for the full release on curseforge in a few days.

https://discord.gg/Vt7BNzJ9
