### ISSUE TITLE
breaking precision mechanism recipie

### ISSUE THREAD

**Issue by Redd56** [Rabbitminers/Extended-Cogs#27]
the percision mechanism recipie override is broken and makes both the gold sheet and iron nugget invalid

**Comment by Redd56** [comment]
it should be "c:gold_plates" and "c:iron_nuggets" on the fabric version atleast

**Comment by Rabbitminers** [comment]
Recipe already matches https://github.com/Fabricators-of-Create/Create/blob/HEAD/src/generated/resources/data/create/recipes/sequenced_assembly/precision_mechanism.json

**Comment by Redd56** [comment]
i already tested with and without extended cogwheels and eith extended cogwheels the recipie completely breaks and wkthout cogwheels everything is completely fine

**Comment by Redd56** [comment]
https://youtu.be/f6YSqGzBSq0

**Comment by TheInfamousAlk** [comment]
This is still a problem.
