### ISSUE TITLE
Implementing new cogwheel materials through KubeJS

### ISSUE THREAD

**Issue by Octelly** [Rabbitminers/Extended-Cogs#28]
Hello, you closed the last issue where I mistakingly asked for the same thing but with datapacks. I have since corrected myself in https://github.com/Rabbitminers/Extended-Flywheels/issues/22 and I am creating this issue as a tracker for KubeJS integration progress (if you are even seriously considering it).

I'd look into it myself, but I'm not particularly familiar with Java. This feature would be a lifesaver however, as I'm currently working on a modpack, that adds tens of modded materials and being only able to use vanilla and Create stuff is a major downside.

I'll link to this new issue in my private modpack issue tracker.

**Comment by Rabbitminers** [comment]
I'm definitely interested in adding this I'll get to work on implementing it for the next update :)

**Comment by Rabbitminers** [comment]
Implemented For Large And Small Cogwheels Ready For Release 2.1.0 (Half shaft & Shaft Cogwheels Will Also Be Available At Release)
