### ISSUE TITLE
[Sugestion] Adding more detailed tags for use in recipes.

### ISSUE THREAD

**Issue by EvanHsieh0415** [Rabbitminers/Extended-Cogs#30]
For Example:
- `#extendedgears:small_cogwheel/...`
  - `#extendedgears:small_shaftless_cogwheel/...`
  - `#extendedgears:small_halfshaft_cogwheel/...`
- `#extendedgears:large_cogwheel/...`
  - `...`

***If it is approved, I can create a PR for this suggestion.***

**Comment by Rabbitminers** [comment]
Sure. I'll get this onto the chopping block for either 2.1.0 or 2.1.1

**Comment by EvanHsieh0415** [comment]
> Sure. I'll get this onto the chopping block for either 2.1.0 or 2.1.1

Which branch is more suitable for me to make changes, `multiloader-1.19.2`?

**Comment by Rabbitminers** [comment]
I've merged the pull request but I'll leave this open until I get round to adding this to datagen
