### ISSUE TITLE
[Bug?] Copper cogwheel have no recipe

### ISSUE THREAD

**Issue by EvanHsieh0415** [Rabbitminers/Extended-Cogs#31]
a part of copper cogwheel have no any recipe.

***If it is confirm, I can create a PR for this report.***

**Comment by Rabbitminers** [comment]
Is this on forge or fabric?

**Comment by EvanHsieh0415** [comment]
> Is this on forge or fabric?

Quilt 1.19.2

**Comment by EvanHsieh0415** [comment]
#33

**Comment by Rabbitminers** [comment]
This may be caused by an incompatibility with the recipe conditions systems. No Support For Quilt Is Planned To Save Time Given Theres Only One Of me

These changes could still be added to a  datapack or kubejs/craftweaker script

**Comment by EvanHsieh0415** [comment]
I found out that the reason is because Create Fabric did not synchronize the tag from 1.18 to 1.19, causing the recipe to fail to load. I have already raised an issue on Create Fabric.

[Fabricators-of-Create/Create#864](https://github.com/Fabricators-of-Create/Create/issues/864)

**Comment by EvanHsieh0415** [comment]
Bruh
[![image](https://user-images.githubusercontent.com/74277414/228816824-438a37a6-7dac-4983-ba0b-4700a50bf169.png)](https://github.com/Fabricators-of-Create/Create/issues/864#issuecomment-1490105336)
https://github.com/Fabricators-of-Create/Create/issues/864#issuecomment-1490105336

**Comment by EvanHsieh0415** [comment]
> This may be caused by an incompatibility with the recipe conditions systems. No Support For Quilt Is Planned To Save Time Given Theres Only One Of me
> 
> These changes could still be added to a datapack or kubejs/craftweaker script

I don't think this has anything to do with whether it's a Quilt issue or not. This is a change made by the Create developers for version 1.19, and according to them, the tag `c:nuggets/copper` was removed in 1.19.
