### ISSUE TITLE
The cogwheels are not working with the sequenze recepies

### ISSUE THREAD

**Issue by RyanFlm** [Rabbitminers/Extended-Cogs#32]
This mod provides cogwheels which can't be used by the sequenced recepies like the one for the "Precision Mechanism". I had to craft the "Oak Cogwheel" to a regular "Cogwheel" first and use that instead.

Is there a way to allow your Cogwheels to? because there was no hint on why this wasn't working and I found the answer after hourly long testing.
Would be great for other players to not experience the same issues I have.

**Comment by Rabbitminers** [comment]
Are you using the latest version (2.0.2)?

**Comment by EvanHsieh0415** [comment]
> This mod provides cogwheels which can't be used by the sequenced recepies like the one for the "Precision Mechanism". I had to craft the "Oak Cogwheel" to a regular "Cogwheel" first and use that instead.
> 
> Is there a way to allow your Cogwheels to? because there was no hint on why this wasn't working and I found the answer after hourly long testing. Would be great for other players to not experience the same issues I have.

What is your mod/game version and mod loader?
If you could provide an example recipe file, that would be better.

**Comment by BusteanHAN** [comment]
Hello, I came to make this issue myself, seems someone beat me to it;
I found my issue on the `extendedgears-2.0.2-1.19.2-0.5.0.ifabric-1.19.2.jar` version. (as the name of that implies, 1.19.2 game version)

In my situation, I was also trying to craft a precision mechanism, and the recipe breaks because the iron nugget step becomes invalid (see pics below)
![image](https://user-images.githubusercontent.com/60746455/228984721-52eadaa5-dffa-4d0a-8a53-8cbcedd4d12e.png)
![image](https://user-images.githubusercontent.com/60746455/228984742-532d8ec8-4bd9-4b27-a6b0-4523dd8a3755.png)

If I go and disable the mod the, the recipe goes back to normal.
P.S. I am playing through curseforge, fabric 0.14.18
P.P.S. The github page is not linked on the curseforge mod page, I had to dig to find this repo

**Comment by RyanFlm** [comment]
> Are you using the latest version (2.0.2)?

No i think that might bei my problem. Will upgrade and test when I find time for it.

**Comment by RyanFlm** [comment]
> > Are you using the latest version (2.0.2)?
> 
> No i think that might bei my problem. Will upgrade and test when I find time for it.

Yep that was my issue. So this can be closed if the issue from BusteanHAN is a different kind of error.

**Comment by ToWipf** [comment]
> Hello, I came to make this issue myself, seems someone beat me to it; I found my issue on the `extendedgears-2.0.2-1.19.2-0.5.0.ifabric-1.19.2.jar` version. (as the name of that implies, 1.19.2 game version)
> 
> In my situation, I was also trying to craft a precision mechanism, and the recipe breaks because the iron nugget step becomes invalid (see pics below) ![image](https://user-images.githubusercontent.com/60746455/228984721-52eadaa5-dffa-4d0a-8a53-8cbcedd4d12e.png) ![image](https://user-images.githubusercontent.com/60746455/228984742-532d8ec8-4bd9-4b27-a6b0-4523dd8a3755.png)
> 
> If I go and disable the mod the, the recipe goes back to normal. P.S. I am playing through curseforge, fabric 0.14.18 P.P.S. The github page is not linked on the curseforge mod page, I had to dig to find this repo

You can 'fix' this by deleting the `precision_mechanism.json` under `data\create\recipes\sequenced_assembly\` inside the .jar file

**Comment by lambsie11** [comment]
Had the exact same issue myself, and it turns out that the modified recipe in this mod uses an incorrect tag string for the 3rd deployment stage in that recipe, using "c:nuggets/iron", instead of "c:iron_nuggets".

**Comment by EvanHsieh0415** [comment]
> Had the exact same issue myself, and it turns out that the modified recipe in this mod uses an incorrect tag string for the 3rd deployment stage in that recipe, using "c:nuggets/iron", instead of "c:iron_nuggets".

yeah, `c:iron_nuggets` is the most formal way of writing
