### ISSUE TITLE
Half Shaft recipe breaks the recipe for piston extension poles

### ISSUE THREAD

**Issue by RickieGamer** [Rabbitminers/Extended-Cogs#35]
![image](https://user-images.githubusercontent.com/90967853/229303988-9787843e-6eb0-4a93-a470-2d8bc7b61873.png)
![image](https://user-images.githubusercontent.com/90967853/229304016-5bcf6fde-e4f3-4292-9006-81896fe3e4c7.png)

**Comment by Rabbitminers** [comment]
Ah thats a bit of an issue, Ill try find some kind of a work around
