### ISSUE TITLE
Create 0.5.1 update made this add-on not working

### ISSUE THREAD

**Issue by RemVan** [Rabbitminers/Extended-Cogs#51]
**Describe the bug**
Addon is not supported Create 0.5.1

**To Reproduce**
I run Create and Create: Extended Cogwheels 

**Expected behavior**
Launching a game with mods

**Screenshots**
+

**Loader & Other Mods:**
 - Forge
 - Create

**Additional context**
-
![eQpk1rPPmvk](https://github.com/Rabbitminers/Extended-Cogwheels/assets/27930521/fa3b101d-434d-4f42-9db6-d424243cef3e)

**Comment by Tesver50** [comment]
Extended coghweels has not been updated to be used with create 5.1 yet

**Comment by RemVan** [comment]
The main thing is that you found out that it causes an error

**Comment by Filostorm** [comment]
Will this be updated on1.18 as well?
