### ISSUE TITLE
Error on loading mod

### ISSUE THREAD

**Issue by DragonGirl7567** [Rabbitminers/Extended-Cogs#57]
**Describe the bug**
Extended Cogwheels (extendedgears) has failed to load correctly

**To Reproduce**
Steps to reproduce the behaviour:
1: launch minecraft with mod
2. (that's it)

**Expected behavior**
When Minecraft finishes loading to the main menu after launch, the error with appear

**Loader & Other Mods:**
 - Forge - 43.2.21
 - Create - 1.19.2-0.5.1.c.jar

**Additional context**
[crash-2023-07-20_11.10.31-fml.txt](https://github.com/Rabbitminers/Extended-Cogwheels/files/12111504/crash-2023-07-20_11.10.31-fml.txt)

**Comment by Rabbitminers** [comment]
Your seem to be using the version for before 0.5.1, Beta releases for the patch have just been uploaded on the discord server and will be moved to curseforge & modrinth later today

**Comment by DragonGirl7567** [comment]
sorry
