### ISSUE TITLE
Incompatible with create 0.5.1

### ISSUE THREAD

**Issue by Ronzaigu** [Rabbitminers/Extended-Cogs#59]
**Describe the bug**
The game ran into an error when loading the mod

**To Reproduce**
1: Install the mod with create 0.5.1
2: Run the game

**Expected behavior**
Well I exptected the mod to work with the newer version of create

**Screenshots**
![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/106442917/d5b069ba-31a2-4ba5-9542-1b538652504c)

**Loader & Other Mods:**
 - Forge

**Additional context**

**Comment by Ronzaigu** [comment]
Here is the crash log
[crash-2023-08-04_14.14.51-fml.txt](https://github.com/Rabbitminers/Extended-Cogwheels/files/12260643/crash-2023-08-04_14.14.51-fml.txt)

**Comment by FoxyFox909** [comment]
Also hoping we get an update to 0.5.1c !

**Comment by Xelbayria** [comment]
One thing to note: 
The Flywheel is now included in Create, so the flywheel mod is no longer needed. The current version of Extended Cogwheel is expected to find the specific version of Flywheel. I don't think it is able to detect the flywheel within Create
Here's the [Fact](https://createmod.net/whywheel/)
