### ISSUE TITLE
Shafts of Encased Mod are Cogwheels now

### ISSUE THREAD

**Issue by f0kx** [Rabbitminers/Extended-Cogs#65]
**Describe the bug**
Shafts of Encased Mod are Cogwheels now. Whenever i place a Shaft of Create Encased Mod it will turn into a Cogwheel

**To Reproduce**
1: Craft a Shaft of Create Encased
2: Place it
3: It will turned Visual into a cogwheel

**Expected behavior**
Shafts should be shafts (visually)

**Screenshots**
![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/14795020/00039737-9b45-4fd2-8eb6-58f642256812)
![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/14795020/5ce5d083-c1a9-4ec6-8d29-3efe80ea8e97)

**Loader & Other Mods:**
 - Forge 43.2.23
 - Nearly all Create Addons
[Create V4-Test.zip](https://github.com/Rabbitminers/Extended-Cogwheels/files/12644328/Create.V4-Test.zip) Thats my Modcollection

**Additional context**
Nothing else to say

**Comment by Rabbitminers** [comment]
Disable the extended cogwheels datafixer in config

**Comment by f0kx** [comment]
no thats wasnt the problem still have the visual bug

![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/14795020/b773f2b9-48cc-4533-a0dd-72cf45bcb1dd)

![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/14795020/80bad23a-6b98-40c2-b593-c9f593644afd)
