### ISSUE TITLE
[Suggestion] Ideas of different cogwheel design

### ISSUE THREAD

**Issue by AlisonHuang777** [Rabbitminers/Extended-Cogs#72]
As the title suggests, I hope that some cogwheel can have models like following images:
![cogwheel sample 1](https://github.com/Rabbitminers/Extended-Cogwheels/assets/51637996/7a7a3e85-ebf4-47ba-a0df-bb6cad623544)  ![cogwheel sample 2](https://github.com/Rabbitminers/Extended-Cogwheels/assets/51637996/f7c5e343-58fa-4900-a926-c47f4d497bcd)
Instead of a solid cylinder.

**Comment by Rabbitminers** [comment]
These are already being worked on. We're planning on making these more functional by allowing the inner shaft to rotate independently from the cogwheel
