### ISSUE TITLE
[Suggestion] Wider cogwheels

### ISSUE THREAD

**Issue by AlisonHuang777** [Rabbitminers/Extended-Cogs#73]
As the title suggests, currently the brass and steel cogwheel variants is a little bit wider than the original wooden one. So I consider that maybe we can go further. (For example, made them as wide as a block)

**Comment by AlisonHuang777** [comment]
(However, that may lead to an issue of them being too thick to be encased with casings, like the brass and steel ones have.)

**Comment by Rabbitminers** [comment]
If, in the future, we use a material that lends itself to being far thicker perhaps well look into this but there are no plans to support this for now due to the added complexity for encasing. Once support is rolled out, you could add this yourself with data packs.
