### ISSUE TITLE
[suggestion] allow setting stress and speed limits for each type of cog

### ISSUE THREAD

**Issue by donoya** [Rabbitminers/Extended-Cogs#74]
I think this feature would be very useful for modpack creators. Essentially the idea is to have in the config files an option to set the stress and speed limits for the cogs. So for example, the iron cog could be configured to have it's own limit to rotation speed or stress, but the limits for rotations peed of the wooden cogwheels could have their own values separately. I'm currently looking to use 1.19.2 to develop my modpack for which I'd need this as a feature, so if this gets implemented, it would be appreciated to have it backported to at least that far.

**Comment by Rabbitminers** [comment]
This is already a feature, it was a config in versions below 2.1 and can now be configured with either datapacks or kubeJS
