### ISSUE TITLE
Crashes addon mods on dedicated server

### ISSUE THREAD

**Issue by ZEROX7** [Rabbitminers/Extended-Cogs#8]
so if i run the server with yyour mod it crashes other create addon mods for some reason
[crash-2022-12-20_16.35.58-fml.txt](https://github.com/Rabbitminers/Extended-Cogs/files/10269786/crash-2022-12-20_16.35.58-fml.txt)

**Comment by Rabbitminers** [comment]
The crash has been patched for v1.1.1, sorry for any inconvenience, the update should be available on curseforge in a few minutes once it is approved
