### ISSUE TITLE
Different cogwheel materials not rendering with Shaders

### ISSUE THREAD

**Issue by jukarr** [Rabbitminers/Extended-Cogs#80]
**Describe the bug**
When applying the different materials to cogwheels while using shaders they don't change at all unless turning off shaders.

**To Reproduce**
1: Install fabric, sodium, iris, etc. and Complementary Reimagined

**Expected behavior**
Cogwheels change material

**Screenshots**
![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/149967785/61f50f6d-a678-4717-a19e-43df4f7ad696)
![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/149967785/22c86da9-3e88-451f-b4f9-8b057d8533f1)

**Loader & Other Mods:**
 - Fabric
 - My own modpack found here: https://legacy.curseforge.com/minecraft/modpacks/cog-con

**Comment by Tr3yMix** [comment]
have you found a fix for this?

**Comment by Dumpling00** [comment]
Same issue here, would like to kindly request acknowledgement.

**Comment by zuperbuu** [comment]
this issue persists.

**Comment by Tr3yMix** [comment]
Install the "Iris & Oculus Flywheel Compat" mod. cogwheels in create use Flywheel.

**Comment by kkempfer** [comment]
This ticket could be closed. Adding ""Iris & Oculus Flywheel Compat" worked on my end: Minecraft 1.19.2 Fabric, Complementary Reimagined shader.
