### ISSUE TITLE
Incompatibility with Create Fabric 0.5.1f

### ISSUE THREAD

**Issue by JensenJ** [Rabbitminers/Extended-Cogs#87]
**Describe the bug**
Create Fabric updated today to 0.5.1f and any addon that interacts with the Create creative mode tab is broken.

**To Reproduce**
1: Download latest Create (0.5.1f at time of writing) and it's dependencies.
2: Download latest extended cogwheels
3. Game does not launch 

**Expected behavior**
Game should launch.

**Logs**
Log: [crash-2024-03-09_20.59.51-client.txt](https://github.com/Rabbitminers/Extended-Cogwheels/files/14547803/crash-2024-03-09_20.59.51-client.txt)
I am aware this crash report mentions other addons but they work without this addon.

**Loader & Other Mods:**
 - Fabric
 - Create 0.5.1f

**Additional context**
Mod works with with other Create addons, as soon as extended cogwheels is added it breaks. It worked before Create updated today.

**Comment by Karotte128** [comment]
can confirm

**Comment by Alastors** [comment]
fixed here: https://www.curseforge.com/minecraft/mc-mods/create-extended-cogwheels-unofficial

**Comment by SafTheLamb** [comment]
Bump, would love to be able to use this mod again ❤️ at least it's an easy plug-and-play when it's updated 😊

**Comment by Alastors** [comment]
> Bump, would love to be able to use this mod again ❤️ at least it's an easy plug-and-play when it's updated 😊

You can using the unofficial release that patched it

**Comment by MimzyFang** [comment]
Since the new releases came out now patching this I think this issue can be closed
