### ISSUE TITLE
Overlapping recipies for cogwheels

### ISSUE THREAD

**Issue by NikZapp** [Rabbitminers/Extended-Cogs#90]
**Describe the bug**
When using a deployer with a plank onto a shaft, the shaftless cogwheel is produced, overwriting the normal create recipe.

**To Reproduce**
1: Place deployer above depot
2: Put a shaft on the depot and give the deployer any plank
3: Activate deployer

**Expected behavior**
The recipe should produce a normal cogwheel.

**Loader & Other Mods:**
 - Does not matter, the issue is in the common source (see below)

**Additional context**
Problematic file: [common/src/generated/resources/data/extendedgears/recipes/deploying/shaftless_cogwheel.json](https://github.com/Rabbitminers/Extended-Cogwheels/blob/multiloader-1.20.1/common/src/generated/resources/data/extendedgears/recipes/deploying/shaftless_cogwheel.json)

**Comment by NikZapp** [comment]
While the fact that using a shaft to produce a shaftless cogwheel is interesting, my factory is now clogged :(

**Comment by Rabbitminers** [comment]
This is a difficult one. On one hand we'd still ideally have a recipe for shaftless cogwheels but it's difficult to make one that's consistent and makes sense. The current decision was made with the idea that to produce cogwheels with shafts you would produce shaftless ones first then apply cogwheels. As you say though this comes at the cost of breaking existing factories which isn't great.

I'd love to hear any alternative recipes you (or anyone else reading this) can come up with

**Comment by Rabbitminers** [comment]
Fixed by #91, thanks
